name: test-base

on:
  workflow_call:
    inputs:
      DATABASE_NAME:
        required: true
        type: string
    secrets:
      AUTHORIZED_KEY:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Add authorized key
        run: echo '${{ secrets.AUTHORIZED_KEY }}' > tests/authorized_key.json
      - name: Run tests
        env:
          DATABASE_NAME: ${{ inputs.DATABASE_NAME }}
          NODE_ENV: development
        run: npm test
